// Auto-generated by: npm run db:generate (prisma generate)
// Do not edit this file manually.
// Run `npm run db:generate` after changing prisma/schema.prisma.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

// Supabase database type stubs — replaced by generated types after `npm run db:generate`.
export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};

export type Tables<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T];

export type Enums<T extends keyof Database["public"]["Enums"]> = Database["public"]["Enums"][T];
