#!/usr/bin/env tsx
/**
 * npm run generate:theme
 *
 * Reads appConfig.theme and regenerates the CSS custom-property blocks in
 * src/app/globals.css. Run this after changing any color or radius value in
 * config/app.config.ts — the UI will automatically use the new tokens.
 */

import { writeFileSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { appConfig } from "../src/config/app.config";

const ROOT = join(import.meta.dirname ?? __dirname, "..");
const CSS_FILE = join(ROOT, "src", "app", "globals.css");

const { colors, borderRadius } = appConfig.theme;

// ── Dark mode variants (lighten/saturate primaries, darken backgrounds) ───────

function lightToDark(hex: string, key: string): string {
  const DARK_OVERRIDES: Record<string, string> = {
    primary: "#818CF8",
    secondary: "#F472B6",
    accent: "#FCD34D",
    background: "#09090B",
    foreground: "#FAFAFA",
    muted: "#27272A",
    border: "#27272A",
    destructive: "#7F1D1D",
  };
  return DARK_OVERRIDES[key] ?? hex;
}

// ── Generate :root block ───────────────────────────────────────────────────────

function buildRoot(): string {
  const lines = Object.entries(colors).map(([key, value]) => {
    const cssVar = `--${key}`;
    return `  ${cssVar.padEnd(18)}: ${value};`;
  });
  lines.push(`  ${"--radius".padEnd(18)}: ${borderRadius};`);
  lines.push(`  ${"--muted-foreground".padEnd(18)}: #71717A;`);
  return `:root {\n${lines.join("\n")}\n}`;
}

// ── Generate .dark block ───────────────────────────────────────────────────────

function buildDark(): string {
  const lines = Object.entries(colors).map(([key, value]) => {
    const cssVar = `--${key}`;
    return `  ${cssVar.padEnd(18)}: ${lightToDark(value, key)};`;
  });
  lines.push(`  ${"--muted-foreground".padEnd(18)}: #A1A1AA;`);
  return `.dark {\n${lines.join("\n")}\n}`;
}

// ── Inject into the CSS file ───────────────────────────────────────────────────

const MARKER_START = "/* ── Design tokens from appConfig.theme";
const MARKER_TAILWIND = "/* ── Tailwind v4 theme mapping";

const existing = readFileSync(CSS_FILE, "utf8");

const tokenSection = `/* ── Design tokens from appConfig.theme ─────────────────────────────────────
   Generated by: npm run generate:theme
   Do not edit the hex values here manually — run \`npm run generate:theme\`
   after changing appConfig.theme.colors to regenerate this file.
   ─────────────────────────────────────────────────────────────────────────── */

${buildRoot()}

${buildDark()}`;

// Replace the section between the design tokens marker and the Tailwind section.
const startIdx = existing.indexOf(MARKER_START);
const endIdx = existing.indexOf(MARKER_TAILWIND);

if (startIdx === -1 || endIdx === -1) {
  console.error("Could not find markers in globals.css. Run this script from the project root.");
  process.exit(1);
}

const updated = existing.slice(0, startIdx) + tokenSection + "\n\n" + existing.slice(endIdx);

writeFileSync(CSS_FILE, updated, "utf8");
console.log(`✓ Theme tokens written to src/app/globals.css`);
console.log(`  primary:    ${colors.primary}`);
console.log(`  secondary:  ${colors.secondary}`);
console.log(`  background: ${colors.background}`);
console.log(`  radius:     ${borderRadius}`);
